### PR TITLE
bugfix notEqualTo

### PR DESCRIPTION
**Pull request by yutin1987**
#15 
Parse.Query.notEqualTo reply is not as expected

### CODE REVIEW

**Comment by roddylindsay** [comment]
isn't notEqualTo the `$ne` query flag?

**Comment by yutin1987** [comment]
@roddylindsay  Sorry, It's doesNotExist, that is my fault.

**Comment by roddylindsay** [comment]
cool, can you add a test as part of this commit, and squash?

**Comment by yutin1987** [comment]
add test and squash, done.

**Comment by TylerBrock** [comment]
thanks

**Pull request merged**
